
# base detos H2 
spring.datasource.url=jdbc:h2:mem:pricesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# console H2, apagar en produccion
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# parametros JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# inicializacion de datos
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# servidor
server.port=8080

# fechas como ISO-8601 en vez de arrays numericos
spring.jackson.serialization.write-dates-as-timestamps=false